name: Build Docker Image

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
    - name: Build Docker image
      run: docker buildx build --platform linux/amd64 -t mqtt-broker-auth .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        echo "Event name: $GITHUB_EVENT_NAME"
        echo "Ref: $GITHUB_REF"

        if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF" == "refs/heads/main" ]]; then
          docker tag mqtt-broker-auth:latest zimbora/mqtt-broker-auth:dev
          docker push zimbora/mqtt-broker-auth:dev

        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_REF" == "refs/heads/main" ]]; then
          docker tag mqtt-broker-auth:latest zimbora/mqtt-broker-auth:dev
          docker push zimbora/mqtt-broker-auth:dev

        elif [[ "$GITHUB_EVENT_NAME" == "create" && "$GITHUB_REF" == refs/tags/* ]]; then
          docker tag mqtt-broker-auth:latest zimbora/mqtt-broker-auth:stage
          docker push zimbora/mqtt-broker-auth:stage

        elif [[ "$GITHUB_EVENT_NAME" == "release" ]]; then
          docker tag mqtt-broker-auth:latest zimbora/mqtt-broker-auth:latest
          docker tag mqtt-broker-auth:latest zimbora/mqtt-broker-auth:${{ env.VERSION }}
          docker push zimbora/mqtt-broker-auth:latest
          docker push zimbora/mqtt-broker-auth:${{ env.VERSION }}

        else
          echo "Triggered by some other event"
        fi