name: Build Docker Image

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Determine build target
      id: set_target
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "BUILD_TARGET=dev" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "BUILD_TARGET=dev" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "create" ]]; then
          # When a tag is created, build as prod
          echo "BUILD_TARGET=prod" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          echo "BUILD_TARGET=prod" >> $GITHUB_ENV
        else
          # Default to dev if unsure
          echo "BUILD_TARGET=dev" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: docker buildx build --platform linux/amd64 --target $BUILD_TARGET -t mqtt-broker-auth:$BUILD_TARGET .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        echo "Event name: $GITHUB_EVENT_NAME"
        echo "Ref: $GITHUB_REF"

        if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF" == "refs/heads/main" ]]; then
          docker tag mqtt-broker-auth:dev zimbora/mqtt-broker-auth:dev
          docker push zimbora/mqtt-broker-auth:dev

        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_REF" == "refs/heads/main" ]]; then
          docker tag mqtt-broker-auth:dev zimbora/mqtt-broker-auth:dev
          docker push zimbora/mqtt-broker-auth:dev

        elif [[ "$GITHUB_EVENT_NAME" == "create" && "$GITHUB_REF" == refs/tags/* ]]; then
          docker tag mqtt-broker-auth:prod zimbora/mqtt-broker-auth:stage-${{ env.VERSION }}
          docker push zimbora/mqtt-broker-auth:stage-${{ env.VERSION }}

        elif [[ "$GITHUB_EVENT_NAME" == "release" ]]; then
          docker tag mqtt-broker-auth:prod zimbora/mqtt-broker-auth:latest
          docker tag mqtt-broker-auth:prod zimbora/mqtt-broker-auth:${{ env.VERSION }}
          docker push zimbora/mqtt-broker-auth:latest
          docker push zimbora/mqtt-broker-auth:${{ env.VERSION }}

        else
          echo "Triggered by some other event"
        fi